version:  '3'
services:
  app:
      build: .
      restart: unless-stopped
      container_name: google_trend_bot
      env_file:
        - .env
      logging:
        driver: "json-file"
        options:
          max-size: "2m"
          max-file: "5"
