services:
  app:
      build: .
      restart: unless-stopped
      container_name: google_trend_bot
      networks:
        - bridge_server
      env_file:
        - .env
      logging:
        driver: "json-file"
        options:
          max-size: "2m"
          max-file: "5"

networks:
  bridge_server:
    external: true
