name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t myapp -f Dockerfile .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 myapp

    - name: Test Service
      run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/health; then
              echo "Service is up!"
              exit 0
            fi
            echo "Waiting for the service to be up..."
            sleep 6
          done
          echo "Service did not start in time"
          exit 1
    
    - name: Check Docker logs (if failed)
      if: failure()
      run: docker logs myapp

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Gibhub Actions - build
        fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ALARM }} # required
      if: always() # Pick up events even if the job fails or is canceled.

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/docker/google_trend_slack_bot/"

    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/docker/google_trend_slack_bot
          echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}" > .env
          echo "FLUENTD_URL=${{ secrets.FLUENTD_URL }}" >> .env
          docker compose down
          docker compose build
          docker compose up -d

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Gibhub Actions - deploy
        fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ALARM }} # required
      if: always() # Pick up events even if the job fails or is canceled.

